name = "PhaseSlopeIndex"
uuid = "d75d2fe3-70b5-44f4-a698-e19bbf534063"
authors = ["IDA Lab TU Berlin"]
version = "0.1.0"

[deps]
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.5"
FFTW = "1.3"
Einsum = "0.4"